### PR TITLE
Change password test

### LINKED ISSUE #19: Create Test Cases for Change Password API
**Is your feature request related to a problem? Please describe.**
We need to test the Change Password API refactored in #17 

**Describe the solution you'd like**
Relevant tests must be added to `tests/users/tests_change_password_api.py`

**Additional context**
Few suggestions for how the tests could be are as follows:
1. Correct email format.
2. Missing fields generate error
3. Password length must be atleast 8 characters.
4. Success for a valid submission. Also verify that the password must actually change post submission.
5. Unregistered Email generating error.
6. Wrong OTP generates error.
and so on..

### PR DESCRIPTION
**Pull request by akhil-maker**
### Description
Tests to check change_password_api with different cases:
- incorrect email format                                                  
- without email                                                  
-  blank email
- unregistered email
- without password                                                  
- short password
- blank password
- without otp
- blank otp
- incorrect otp
- correct data and otp generation using forgot_password_api with check that password changed successfully using login api                                        

**Type of Change:** (Delete irrelevant options)
- Code
- Testing

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested locally and checked that all the tests are passed.
```Log:```

```Creating test database for alias 'default'...
System check identified no issues (0 silenced).
............
===================== Mock email service =====================
Recipients: ['test@gmail.com']
Subject: E-Cell NITRR
Body: Your OTP for E-Cell NIT Raipur portal is 9262.
==============================================================
......
===================== Mock email service =====================
Recipients: ['test@gmail.com']
Subject: E-Cell NITRR
Body: Your OTP for E-Cell NIT Raipur portal is 5034.
==============================================================
........
===================== Mock email service =====================
Recipients: ['user234@example.com']
Subject: E-Cell NITRR
Body: Your OTP for E-Cell NIT Raipur portal is 8218.
==============================================================
......
===================== Mock email service =====================
Recipients: ['user234@example.com']
Subject: E-Cell NITRR
Body: Your OTP for E-Cell NIT Raipur portal is 4370.
==============================================================
...
===================== Mock email service =====================
Recipients: ['crash.test.dummy@gmail.com']
Subject: E-Cell NITRR
Body: Your OTP for E-Cell NIT Raipur portal is 8756.
==============================================================
.....
----------------------------------------------------------------------
Ran 40 tests in 3.661s
OK
Destroying test database for alias 'default'...
```

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by akhil-maker** [comment]
@anshsrtv and @priyanshisharma Please give your reviews.

**Review by anshsrtv — COMMENTED** [review]
Nice Job @akhil-maker 🔥 But, I would suggest using better variable names like `old_password`, `new_password`, `forget_password_response`, `invalid_otp` etc.

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
Great work @akhil-maker 🎉 
Please also add a test for *Password being too short/blank* and also consider improving variable names as @anshsrtv pointed out, and linting the code as well.

**Comment by akhil-maker** [comment]
> Nice Job @akhil-maker 🔥 But, I would suggest using better variable names like `old_password`, `new_password`, `forget_password_response`, `invalid_otp` etc.

@anshsrtv Done sir!

**Comment by akhil-maker** [comment]
> Great work @akhil-maker 🎉
> Please also add a test for _Password being too short/blank_ and also consider improving variable names as @anshsrtv pointed out, and linting the code as well.

@priyanshisharma It's completed ma'am, now review it.

**Review by priyanshisharma — APPROVED** [review]
Looks good to me 🎉

**Review by anshsrtv — COMMENTED** [review]
@akhil-maker You got me wrong. I asked you to change the names of the variables instead of changing their values.
`self.password` changes to` self.new_password`
Similarly, `self.otp` changes to `self.invalid_otp`

**Comment by akhil-maker** [comment]
> @akhil-maker You got me wrong. I asked you to change the names of the variables instead of changing their values.
> `self.password` changes to` self.new_password`
> Similarly, `self.otp` changes to `self.invalid_otp`

Oh! Ok sir, now it's completed

**Review by anshsrtv — APPROVED** [review]

**Pull request merged**
