### PR TITLE
feat: Added auth tests for Login API

### LINKED ISSUE #9: Add testcases for Login API
**Is your feature request related to a problem? Please describe.**

Taking [Teesco Backend](https://github.com/ECellNitrr/teesco-backend/) as a reference, test the User Login API.

**Describe the solution you'd like**

Create a file in `/tests/users/` named `tests_login_api.py` and create testcases for the API.

**Additional context**

https://github.com/ECellNitrr/teesco-backend/blob/dev/tests/users/tests_login_api.py

### PR DESCRIPTION
**Pull request by sahil9001**
### Description
This commit includes testing code for Authentication API. Also includes a new route for checking authentication.

**Type of Change:** (Delete irrelevant options)
- Code
- Testing
- Documentation

**Code/Quality Assurance Only** (Delete irrelevant options)

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Ran `python manage.py test` and got the following output:

```
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
............
----------------------------------------------------------------------
Ran 12 tests in 0.788s

OK
Destroying test database for alias 'default'...
```

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [x] Update Swagger documentation and the exported file at /docs folder
- [ ] Update requirements.txt

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
The tests are failing, the User model here is a little different from `teesco-backend`, please do the required changes.

**Comment by sahil9001** [comment]
> The tests are failing, the User model here is a little different from `teesco-backend`, please do the required changes. they are passing for you as you haven't added `__init__.py` in your `users` folder. The tests you wrote aren't actually running in your machine.

Oh lol, I missed that

**Review by priyanshisharma — APPROVED** [review]
Looks good to me 🚀 👍

**Review by anshsrtv — APPROVED** [review]
Great job 🏅 @sahil9001

**Pull request merged**
